"""empty message

Revision ID: dacc98812140
Revises: 22e12086fb7a
Create Date: 2020-11-02 09:01:04.967428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacc98812140'
down_revision = '22e12086fb7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectdetails', sa.Column('report', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projectdetails', 'report')
    # ### end Alembic commands ###
